spring:
  datasource:
    url: jdbc:mysql://192.168.100.233:3306/server_management?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

minio:
  url: http://192.168.100.233:9000
  username: admin
  password: 12345678

tomcatfile:
  savePath: webapps/ROOT.war

swagger:
  enable: true