spring:
  datasource:
    url: jdbc:mysql://192.168.0.232:3306/server_management?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: rjsoft

minio:
  url: http://32.0.7.21:9000
  username: zhjzMinio
  password: Zhjz@Minio#$

tomcatfile:
  savePath: webapps/ROOT.war

swagger:
  enable: true